version: 0.2
phases:
  install:
    runtime-versions:
       python: 3.10
  pre_build:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y python3 python3-pip wget openjdk-8-jdk curl
      - python3 -m pip install --upgrade pip
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - python3 -m pip install awscli
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
      - unzip ./sonar-scanner-cli-4.6.0.2311-linux.zip
      - mv sonar-scanner-4.6.0.2311-linux sonar-scanner
      - export PATH=$PATH:./sonar-scanner/bin
      - sudo apt-get install -y jq
      
  build:
    commands:
      - echo "sonar.coverage.exclusions=**/*.py" >> sonar-project.properties
      - sonar-scanner -Dsonar.login=6b42cb270dc085d355bbc50c494bea0191b29f7e -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=venky897 -Dsonar.organization=venky897 
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=venky897 >result.json
      - cat result.json
      - if ! command -v jq >/dev/null 2>&1; then echo "jq not found"; exit 1; fi
      - if [ $(jq -r'.projectStatus.status' result.json) = "ERROR" ]; then $CODEBUILD_BUILD_SUCCEEDING -eq 0; fi
